# Generated by Django 4.0.3 on 2022-04-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_file', models.CharField(max_length=200)),
                ('p_text', models.CharField(max_length=400)),
                ('p_date', models.DateTimeField()),
            ],
        ),
    ]
