# Generated by Django 4.0.3 on 2022-04-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_file', models.CharField(max_length=200)),
                ('a_text', models.CharField(max_length=400)),
            ],
        ),
    ]
